// Generated by scripts/generate-brand-assets.mjs from public/brand/lumina-logo-source.png.
// Do not edit by hand — replace the source logo and run `npm run brand`.
export const BRAND_COLORS = { navy: "#042045", gold: "#CC9F2F" } as const;

export const MARK_VIEWBOX = { width: 567, height: 665 } as const;

/** Pixel size of public/brand/lumina-logo*.png (mark + wordmark lockup). */
export const LOGO_FULL_SIZE = { width: 1134, height: 982 } as const;

/** Pixel size of public/brand/lumina-wordmark*.png (the "LUMINA HOLDINGS" text on its own). */
export const WORDMARK_SIZE = { width: 1134, height: 263 } as const;

export const MARK_SHAPES: ReadonlyArray<{ color: "navy" | "gold"; d: string }> = [
  { color: "navy", d: "M278 49L279 45L282 40L286 37L292 35L430 0L441 0L445 2L450 7L457 27L561 374L567 397L567 401L566 402L565 402L560 397L523 355L362 160L283 63L279 56Z" },
  { color: "navy", d: "M69 199L72 193L76 189L82 185L211 105L217 103L225 103L228 104L234 108L371 247L453 332L512 395L534 420L532 420L489 402L263 302L90 224L76 217L71 212L69 207Z" },
  { color: "gold", d: "M0 423L3 416L6 412L99 299L105 293L111 290L118 290L372 390L462 426L486 436L489 438L301 439L12 439L7 437L2 432L0 427Z" },
  { color: "navy", d: "M115 586L154 481L157 475L162 470L167 468L374 468L473 469L488 470L475 476L433 492L132 602L126 602L120 599L116 594Z" },
  { color: "gold", d: "M309 587L311 582L317 577L454 525L513 503L515 503L362 661L356 662L351 659L311 595L309 590Z" },
  { color: "navy", d: "M455 629L459 623L538 545L551 533L552 533L552 537L550 543L518 626L506 656L503 662L501 664L499 665L492 665L483 659L456 637L455 635Z" },
];
