import type { BusRoute, Country, EventListing } from "./types";

export const countries: Country[] = [
  { code: "MW", name: "Malawi", currency: "MWK", flag: "🇲🇼", live: true },
  { code: "ZM", name: "Zambia", currency: "ZMW", flag: "🇿🇲", live: true },
  { code: "ZW", name: "Zimbabwe", currency: "USD", flag: "🇿🇼", live: true },
  { code: "MZ", name: "Mozambique", currency: "MZN", flag: "🇲🇿", live: false },
  { code: "TZ", name: "Tanzania", currency: "TZS", flag: "🇹🇿", live: false },
  { code: "ZA", name: "South Africa", currency: "ZAR", flag: "🇿🇦", live: false },
  { code: "BW", name: "Botswana", currency: "BWP", flag: "🇧🇼", live: false },
  { code: "NA", name: "Namibia", currency: "NAD", flag: "🇳🇦", live: false },
];

export const popularRoutes: BusRoute[] = [
  {
    id: "r1",
    origin: "Lilongwe",
    destination: "Blantyre",
    operator: "AXA Coach",
    duration: "4h 30m",
    fromPrice: 18000,
    currency: "MWK",
    departures: 9,
    rating: 4.6,
  },
  {
    id: "r2",
    origin: "Blantyre",
    destination: "Mzuzu",
    operator: "Nyasa Express",
    duration: "8h 15m",
    fromPrice: 25000,
    currency: "MWK",
    departures: 4,
    rating: 4.3,
  },
  {
    id: "r3",
    origin: "Lilongwe",
    destination: "Lusaka",
    operator: "Munorurama Coach",
    duration: "9h 00m",
    fromPrice: 45000,
    currency: "MWK",
    departures: 2,
    rating: 4.5,
  },
  {
    id: "r4",
    origin: "Lusaka",
    destination: "Harare",
    operator: "Intercape Cross-Border",
    duration: "11h 45m",
    fromPrice: 320,
    currency: "ZMW",
    departures: 3,
    rating: 4.7,
  },
  {
    id: "r5",
    origin: "Mzuzu",
    destination: "Karonga",
    operator: "Northern Link",
    duration: "3h 10m",
    fromPrice: 9500,
    currency: "MWK",
    departures: 6,
    rating: 4.1,
  },
  {
    id: "r6",
    origin: "Lilongwe",
    destination: "Zomba",
    operator: "AXA Coach",
    duration: "3h 45m",
    fromPrice: 14500,
    currency: "MWK",
    departures: 7,
    rating: 4.4,
  },
];

export const trendingEvents: EventListing[] = [
  {
    id: "e1",
    title: "Lake of Stars Festival",
    category: "Music Festival",
    venue: "Sunbird Nkopola",
    city: "Mangochi",
    countryCode: "MW",
    date: "2026-10-02",
    fromPrice: 35000,
    currency: "MWK",
    status: "selling-fast",
  },
  {
    id: "e2",
    title: "Blantyre Comedy Night",
    category: "Comedy",
    venue: "Blantyre Sports Club",
    city: "Blantyre",
    countryCode: "MW",
    date: "2026-09-19",
    fromPrice: 12000,
    currency: "MWK",
    status: "on-sale",
  },
  {
    id: "e3",
    title: "Copperbelt Gospel Explosion",
    category: "Gospel",
    venue: "Levy Mwanawasa Stadium",
    city: "Ndola",
    countryCode: "ZM",
    date: "2026-11-08",
    fromPrice: 150,
    currency: "ZMW",
    status: "on-sale",
  },
  {
    id: "e4",
    title: "Harare Business Summit",
    category: "Conference",
    venue: "Rainbow Towers",
    city: "Harare",
    countryCode: "ZW",
    date: "2026-09-28",
    fromPrice: 80,
    currency: "USD",
    status: "sold-out",
  },
];

export const howItWorks = [
  {
    step: "01",
    title: "Search & compare",
    body: "Compare bus operators, routes, and events side by side, with live seat availability across the region.",
  },
  {
    step: "02",
    title: "Book & pay your way",
    body: "Pay online by card or mobile money, or reserve now and pay at any Lumiticket retail agent.",
  },
  {
    step: "03",
    title: "Get your QR ticket",
    body: "A secure, forgery-resistant QR ticket lands in your account instantly, available offline too.",
  },
  {
    step: "04",
    title: "Travel, attend, track",
    body: "Scan in at boarding or the gate, and track parcels in real time until they're signed for.",
  },
];
